apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: employee-service
  name: employee-service
  namespace: employee-service
spec:
  type: NodePort
  ports:
  - name: "8002"
    port: 8002
    targetPort: 8002
    nodePort: 32000
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    io.kompose.service: employee-service
status:
  loadBalancer: {}
